// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvejuhnvvqxoqasosscz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZWp1aG52dnF4b3Fhc29zc2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTQ1MTUsImV4cCI6MjA3MDczMDUxNX0.I_N5DB3TKZg7zakuMR_JZ16J9MbW98oaJbXxEG3LaiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});